//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SoapyBusApp.Droid.ie.dublinbus.rtpi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DublinBusRTPIServiceSoap", Namespace="http://dublinbus.ie/")]
    public partial class DublinBusRTPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRealTimeStopDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRealTimeStopData_ForceLineNoteVisitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoutesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoutesIncNiteLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoutesIncNiteLink_MobileFareCalcOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDestinationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDestinationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStopDataByAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStopDataByRouteAndDirectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStopDataByRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoutesServicedByStopNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartTimerOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopTimerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCurrentSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback postXMLDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearCacheItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DublinBusRTPIService() {
            this.Url = "http://rtpi.dublinbus.ie/DublinBusRTPIService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestServiceCompletedEventHandler TestServiceCompleted;
        
        /// <remarks/>
        public event GetRealTimeStopDataCompletedEventHandler GetRealTimeStopDataCompleted;
        
        /// <remarks/>
        public event GetRealTimeStopData_ForceLineNoteVisitCompletedEventHandler GetRealTimeStopData_ForceLineNoteVisitCompleted;
        
        /// <remarks/>
        public event GetRoutesCompletedEventHandler GetRoutesCompleted;
        
        /// <remarks/>
        public event GetRoutesIncNiteLinkCompletedEventHandler GetRoutesIncNiteLinkCompleted;
        
        /// <remarks/>
        public event GetRoutesIncNiteLink_MobileFareCalcCompletedEventHandler GetRoutesIncNiteLink_MobileFareCalcCompleted;
        
        /// <remarks/>
        public event GetDestinationsCompletedEventHandler GetDestinationsCompleted;
        
        /// <remarks/>
        public event GetAllDestinationsCompletedEventHandler GetAllDestinationsCompleted;
        
        /// <remarks/>
        public event GetStopDataByAddressCompletedEventHandler GetStopDataByAddressCompleted;
        
        /// <remarks/>
        public event GetStopDataByRouteAndDirectionCompletedEventHandler GetStopDataByRouteAndDirectionCompleted;
        
        /// <remarks/>
        public event GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventHandler GetStopDataByRouteAndDirection_MobileFareCalcCompleted;
        
        /// <remarks/>
        public event GetStopDataByRouteCompletedEventHandler GetStopDataByRouteCompleted;
        
        /// <remarks/>
        public event GetRoutesServicedByStopNumberCompletedEventHandler GetRoutesServicedByStopNumberCompleted;
        
        /// <remarks/>
        public event StartTimerCompletedEventHandler StartTimerCompleted;
        
        /// <remarks/>
        public event StopTimerCompletedEventHandler StopTimerCompleted;
        
        /// <remarks/>
        public event GetCurrentSettingsCompletedEventHandler GetCurrentSettingsCompleted;
        
        /// <remarks/>
        public event SetCurrentSettingsCompletedEventHandler SetCurrentSettingsCompleted;
        
        /// <remarks/>
        public event postXMLDataCompletedEventHandler postXMLDataCompleted;
        
        /// <remarks/>
        public event ClearCacheItemCompletedEventHandler ClearCacheItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/TestService", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestService() {
            object[] results = this.Invoke("TestService", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestServiceAsync() {
            this.TestServiceAsync(null);
        }
        
        /// <remarks/>
        public void TestServiceAsync(object userState) {
            if ((this.TestServiceOperationCompleted == null)) {
                this.TestServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestServiceOperationCompleted);
            }
            this.InvokeAsync("TestService", new object[0], this.TestServiceOperationCompleted, userState);
        }
        
        private void OnTestServiceOperationCompleted(object arg) {
            if ((this.TestServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestServiceCompleted(this, new TestServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRealTimeStopData", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRealTimeStopData(int stopId, bool forceRefresh) {
            object[] results = this.Invoke("GetRealTimeStopData", new object[] {
                        stopId,
                        forceRefresh});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRealTimeStopDataAsync(int stopId, bool forceRefresh) {
            this.GetRealTimeStopDataAsync(stopId, forceRefresh, null);
        }
        
        /// <remarks/>
        public void GetRealTimeStopDataAsync(int stopId, bool forceRefresh, object userState) {
            if ((this.GetRealTimeStopDataOperationCompleted == null)) {
                this.GetRealTimeStopDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRealTimeStopDataOperationCompleted);
            }
            this.InvokeAsync("GetRealTimeStopData", new object[] {
                        stopId,
                        forceRefresh}, this.GetRealTimeStopDataOperationCompleted, userState);
        }
        
        private void OnGetRealTimeStopDataOperationCompleted(object arg) {
            if ((this.GetRealTimeStopDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRealTimeStopDataCompleted(this, new GetRealTimeStopDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRealTimeStopData_ForceLineNoteVisit", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRealTimeStopData_ForceLineNoteVisit(int stopId, bool forceRefresh, bool forceLineNoteVisit) {
            object[] results = this.Invoke("GetRealTimeStopData_ForceLineNoteVisit", new object[] {
                        stopId,
                        forceRefresh,
                        forceLineNoteVisit});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRealTimeStopData_ForceLineNoteVisitAsync(int stopId, bool forceRefresh, bool forceLineNoteVisit) {
            this.GetRealTimeStopData_ForceLineNoteVisitAsync(stopId, forceRefresh, forceLineNoteVisit, null);
        }
        
        /// <remarks/>
        public void GetRealTimeStopData_ForceLineNoteVisitAsync(int stopId, bool forceRefresh, bool forceLineNoteVisit, object userState) {
            if ((this.GetRealTimeStopData_ForceLineNoteVisitOperationCompleted == null)) {
                this.GetRealTimeStopData_ForceLineNoteVisitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRealTimeStopData_ForceLineNoteVisitOperationCompleted);
            }
            this.InvokeAsync("GetRealTimeStopData_ForceLineNoteVisit", new object[] {
                        stopId,
                        forceRefresh,
                        forceLineNoteVisit}, this.GetRealTimeStopData_ForceLineNoteVisitOperationCompleted, userState);
        }
        
        private void OnGetRealTimeStopData_ForceLineNoteVisitOperationCompleted(object arg) {
            if ((this.GetRealTimeStopData_ForceLineNoteVisitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRealTimeStopData_ForceLineNoteVisitCompleted(this, new GetRealTimeStopData_ForceLineNoteVisitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRoutes", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoutesResponse GetRoutes(string filter) {
            object[] results = this.Invoke("GetRoutes", new object[] {
                        filter});
            return ((RoutesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoutesAsync(string filter) {
            this.GetRoutesAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetRoutesAsync(string filter, object userState) {
            if ((this.GetRoutesOperationCompleted == null)) {
                this.GetRoutesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoutesOperationCompleted);
            }
            this.InvokeAsync("GetRoutes", new object[] {
                        filter}, this.GetRoutesOperationCompleted, userState);
        }
        
        private void OnGetRoutesOperationCompleted(object arg) {
            if ((this.GetRoutesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoutesCompleted(this, new GetRoutesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRoutesIncNiteLink", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoutesResponse GetRoutesIncNiteLink(string filter) {
            object[] results = this.Invoke("GetRoutesIncNiteLink", new object[] {
                        filter});
            return ((RoutesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoutesIncNiteLinkAsync(string filter) {
            this.GetRoutesIncNiteLinkAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetRoutesIncNiteLinkAsync(string filter, object userState) {
            if ((this.GetRoutesIncNiteLinkOperationCompleted == null)) {
                this.GetRoutesIncNiteLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoutesIncNiteLinkOperationCompleted);
            }
            this.InvokeAsync("GetRoutesIncNiteLink", new object[] {
                        filter}, this.GetRoutesIncNiteLinkOperationCompleted, userState);
        }
        
        private void OnGetRoutesIncNiteLinkOperationCompleted(object arg) {
            if ((this.GetRoutesIncNiteLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoutesIncNiteLinkCompleted(this, new GetRoutesIncNiteLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRoutesIncNiteLink_MobileFareCalc", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoutesResponse GetRoutesIncNiteLink_MobileFareCalc(string filter) {
            object[] results = this.Invoke("GetRoutesIncNiteLink_MobileFareCalc", new object[] {
                        filter});
            return ((RoutesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoutesIncNiteLink_MobileFareCalcAsync(string filter) {
            this.GetRoutesIncNiteLink_MobileFareCalcAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetRoutesIncNiteLink_MobileFareCalcAsync(string filter, object userState) {
            if ((this.GetRoutesIncNiteLink_MobileFareCalcOperationCompleted == null)) {
                this.GetRoutesIncNiteLink_MobileFareCalcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoutesIncNiteLink_MobileFareCalcOperationCompleted);
            }
            this.InvokeAsync("GetRoutesIncNiteLink_MobileFareCalc", new object[] {
                        filter}, this.GetRoutesIncNiteLink_MobileFareCalcOperationCompleted, userState);
        }
        
        private void OnGetRoutesIncNiteLink_MobileFareCalcOperationCompleted(object arg) {
            if ((this.GetRoutesIncNiteLink_MobileFareCalcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoutesIncNiteLink_MobileFareCalcCompleted(this, new GetRoutesIncNiteLink_MobileFareCalcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetDestinations", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DestinationsResponse GetDestinations(string filter) {
            object[] results = this.Invoke("GetDestinations", new object[] {
                        filter});
            return ((DestinationsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetDestinationsAsync(string filter) {
            this.GetDestinationsAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetDestinationsAsync(string filter, object userState) {
            if ((this.GetDestinationsOperationCompleted == null)) {
                this.GetDestinationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDestinationsOperationCompleted);
            }
            this.InvokeAsync("GetDestinations", new object[] {
                        filter}, this.GetDestinationsOperationCompleted, userState);
        }
        
        private void OnGetDestinationsOperationCompleted(object arg) {
            if ((this.GetDestinationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDestinationsCompleted(this, new GetDestinationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetAllDestinations", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DestinationsResponse GetAllDestinations() {
            object[] results = this.Invoke("GetAllDestinations", new object[0]);
            return ((DestinationsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDestinationsAsync() {
            this.GetAllDestinationsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDestinationsAsync(object userState) {
            if ((this.GetAllDestinationsOperationCompleted == null)) {
                this.GetAllDestinationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDestinationsOperationCompleted);
            }
            this.InvokeAsync("GetAllDestinations", new object[0], this.GetAllDestinationsOperationCompleted, userState);
        }
        
        private void OnGetAllDestinationsOperationCompleted(object arg) {
            if ((this.GetAllDestinationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDestinationsCompleted(this, new GetAllDestinationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetStopDataByAddress", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStopDataByAddress(string address) {
            object[] results = this.Invoke("GetStopDataByAddress", new object[] {
                        address});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetStopDataByAddressAsync(string address) {
            this.GetStopDataByAddressAsync(address, null);
        }
        
        /// <remarks/>
        public void GetStopDataByAddressAsync(string address, object userState) {
            if ((this.GetStopDataByAddressOperationCompleted == null)) {
                this.GetStopDataByAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStopDataByAddressOperationCompleted);
            }
            this.InvokeAsync("GetStopDataByAddress", new object[] {
                        address}, this.GetStopDataByAddressOperationCompleted, userState);
        }
        
        private void OnGetStopDataByAddressOperationCompleted(object arg) {
            if ((this.GetStopDataByAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStopDataByAddressCompleted(this, new GetStopDataByAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetStopDataByRouteAndDirection", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStopDataByRouteAndDirection(string route, string direction) {
            object[] results = this.Invoke("GetStopDataByRouteAndDirection", new object[] {
                        route,
                        direction});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAndDirectionAsync(string route, string direction) {
            this.GetStopDataByRouteAndDirectionAsync(route, direction, null);
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAndDirectionAsync(string route, string direction, object userState) {
            if ((this.GetStopDataByRouteAndDirectionOperationCompleted == null)) {
                this.GetStopDataByRouteAndDirectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStopDataByRouteAndDirectionOperationCompleted);
            }
            this.InvokeAsync("GetStopDataByRouteAndDirection", new object[] {
                        route,
                        direction}, this.GetStopDataByRouteAndDirectionOperationCompleted, userState);
        }
        
        private void OnGetStopDataByRouteAndDirectionOperationCompleted(object arg) {
            if ((this.GetStopDataByRouteAndDirectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStopDataByRouteAndDirectionCompleted(this, new GetStopDataByRouteAndDirectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetStopDataByRouteAndDirection_MobileFareCalc", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStopDataByRouteAndDirection_MobileFareCalc(string route, string direction) {
            object[] results = this.Invoke("GetStopDataByRouteAndDirection_MobileFareCalc", new object[] {
                        route,
                        direction});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAndDirection_MobileFareCalcAsync(string route, string direction) {
            this.GetStopDataByRouteAndDirection_MobileFareCalcAsync(route, direction, null);
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAndDirection_MobileFareCalcAsync(string route, string direction, object userState) {
            if ((this.GetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted == null)) {
                this.GetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted);
            }
            this.InvokeAsync("GetStopDataByRouteAndDirection_MobileFareCalc", new object[] {
                        route,
                        direction}, this.GetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted, userState);
        }
        
        private void OnGetStopDataByRouteAndDirection_MobileFareCalcOperationCompleted(object arg) {
            if ((this.GetStopDataByRouteAndDirection_MobileFareCalcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStopDataByRouteAndDirection_MobileFareCalcCompleted(this, new GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetStopDataByRoute", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStopDataByRoute(string route) {
            object[] results = this.Invoke("GetStopDataByRoute", new object[] {
                        route});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAsync(string route) {
            this.GetStopDataByRouteAsync(route, null);
        }
        
        /// <remarks/>
        public void GetStopDataByRouteAsync(string route, object userState) {
            if ((this.GetStopDataByRouteOperationCompleted == null)) {
                this.GetStopDataByRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStopDataByRouteOperationCompleted);
            }
            this.InvokeAsync("GetStopDataByRoute", new object[] {
                        route}, this.GetStopDataByRouteOperationCompleted, userState);
        }
        
        private void OnGetStopDataByRouteOperationCompleted(object arg) {
            if ((this.GetStopDataByRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStopDataByRouteCompleted(this, new GetStopDataByRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetRoutesServicedByStopNumber", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Route[] GetRoutesServicedByStopNumber(int stopId) {
            object[] results = this.Invoke("GetRoutesServicedByStopNumber", new object[] {
                        stopId});
            return ((Route[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRoutesServicedByStopNumberAsync(int stopId) {
            this.GetRoutesServicedByStopNumberAsync(stopId, null);
        }
        
        /// <remarks/>
        public void GetRoutesServicedByStopNumberAsync(int stopId, object userState) {
            if ((this.GetRoutesServicedByStopNumberOperationCompleted == null)) {
                this.GetRoutesServicedByStopNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoutesServicedByStopNumberOperationCompleted);
            }
            this.InvokeAsync("GetRoutesServicedByStopNumber", new object[] {
                        stopId}, this.GetRoutesServicedByStopNumberOperationCompleted, userState);
        }
        
        private void OnGetRoutesServicedByStopNumberOperationCompleted(object arg) {
            if ((this.GetRoutesServicedByStopNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoutesServicedByStopNumberCompleted(this, new GetRoutesServicedByStopNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/StartTimer", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StartTimer() {
            object[] results = this.Invoke("StartTimer", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StartTimerAsync() {
            this.StartTimerAsync(null);
        }
        
        /// <remarks/>
        public void StartTimerAsync(object userState) {
            if ((this.StartTimerOperationCompleted == null)) {
                this.StartTimerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartTimerOperationCompleted);
            }
            this.InvokeAsync("StartTimer", new object[0], this.StartTimerOperationCompleted, userState);
        }
        
        private void OnStartTimerOperationCompleted(object arg) {
            if ((this.StartTimerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartTimerCompleted(this, new StartTimerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/StopTimer", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StopTimer() {
            object[] results = this.Invoke("StopTimer", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StopTimerAsync() {
            this.StopTimerAsync(null);
        }
        
        /// <remarks/>
        public void StopTimerAsync(object userState) {
            if ((this.StopTimerOperationCompleted == null)) {
                this.StopTimerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopTimerOperationCompleted);
            }
            this.InvokeAsync("StopTimer", new object[0], this.StopTimerOperationCompleted, userState);
        }
        
        private void OnStopTimerOperationCompleted(object arg) {
            if ((this.StopTimerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopTimerCompleted(this, new StopTimerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/GetCurrentSettings", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCurrentSettings() {
            object[] results = this.Invoke("GetCurrentSettings", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentSettingsAsync() {
            this.GetCurrentSettingsAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentSettingsAsync(object userState) {
            if ((this.GetCurrentSettingsOperationCompleted == null)) {
                this.GetCurrentSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentSettingsOperationCompleted);
            }
            this.InvokeAsync("GetCurrentSettings", new object[0], this.GetCurrentSettingsOperationCompleted, userState);
        }
        
        private void OnGetCurrentSettingsOperationCompleted(object arg) {
            if ((this.GetCurrentSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentSettingsCompleted(this, new GetCurrentSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/SetCurrentSettings", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCurrentSettings(string[] values) {
            this.Invoke("SetCurrentSettings", new object[] {
                        values});
        }
        
        /// <remarks/>
        public void SetCurrentSettingsAsync(string[] values) {
            this.SetCurrentSettingsAsync(values, null);
        }
        
        /// <remarks/>
        public void SetCurrentSettingsAsync(string[] values, object userState) {
            if ((this.SetCurrentSettingsOperationCompleted == null)) {
                this.SetCurrentSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCurrentSettingsOperationCompleted);
            }
            this.InvokeAsync("SetCurrentSettings", new object[] {
                        values}, this.SetCurrentSettingsOperationCompleted, userState);
        }
        
        private void OnSetCurrentSettingsOperationCompleted(object arg) {
            if ((this.SetCurrentSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCurrentSettingsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/postXMLData", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postXMLData(string destinationUrl, string requestXml) {
            object[] results = this.Invoke("postXMLData", new object[] {
                        destinationUrl,
                        requestXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void postXMLDataAsync(string destinationUrl, string requestXml) {
            this.postXMLDataAsync(destinationUrl, requestXml, null);
        }
        
        /// <remarks/>
        public void postXMLDataAsync(string destinationUrl, string requestXml, object userState) {
            if ((this.postXMLDataOperationCompleted == null)) {
                this.postXMLDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostXMLDataOperationCompleted);
            }
            this.InvokeAsync("postXMLData", new object[] {
                        destinationUrl,
                        requestXml}, this.postXMLDataOperationCompleted, userState);
        }
        
        private void OnpostXMLDataOperationCompleted(object arg) {
            if ((this.postXMLDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postXMLDataCompleted(this, new postXMLDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dublinbus.ie/ClearCacheItem", RequestNamespace="http://dublinbus.ie/", ResponseNamespace="http://dublinbus.ie/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ClearCacheItem(string key) {
            object[] results = this.Invoke("ClearCacheItem", new object[] {
                        key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ClearCacheItemAsync(string key) {
            this.ClearCacheItemAsync(key, null);
        }
        
        /// <remarks/>
        public void ClearCacheItemAsync(string key, object userState) {
            if ((this.ClearCacheItemOperationCompleted == null)) {
                this.ClearCacheItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearCacheItemOperationCompleted);
            }
            this.InvokeAsync("ClearCacheItem", new object[] {
                        key}, this.ClearCacheItemOperationCompleted, userState);
        }
        
        private void OnClearCacheItemOperationCompleted(object arg) {
            if ((this.ClearCacheItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearCacheItemCompleted(this, new ClearCacheItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class RoutesResponse {
        
        private Route[] routesField;
        
        /// <remarks/>
        public Route[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class Route {
        
        private string numberField;
        
        private string directionField;
        
        private int seqNumberField;
        
        private string towardsField;
        
        private string fromField;
        
        private Destination[] destinationsField;
        
        private string descriptionField;
        
        private bool isStagedField;
        
        private string outboundPatternField;
        
        private string outboundFromField;
        
        private string outboundTowardsField;
        
        private string outboundViaField;
        
        private string inboundPatternField;
        
        private string inboundFromField;
        
        private string inboundTowardsField;
        
        private string inboundViaField;
        
        private bool isXpressoField;
        
        private bool isNitelinkField;
        
        private bool isMinimumFareField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public int SeqNumber {
            get {
                return this.seqNumberField;
            }
            set {
                this.seqNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Towards {
            get {
                return this.towardsField;
            }
            set {
                this.towardsField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Destinations", IsNullable=true)]
        public Destination[] Destinations {
            get {
                return this.destinationsField;
            }
            set {
                this.destinationsField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsStaged {
            get {
                return this.isStagedField;
            }
            set {
                this.isStagedField = value;
            }
        }
        
        /// <remarks/>
        public string OutboundPattern {
            get {
                return this.outboundPatternField;
            }
            set {
                this.outboundPatternField = value;
            }
        }
        
        /// <remarks/>
        public string OutboundFrom {
            get {
                return this.outboundFromField;
            }
            set {
                this.outboundFromField = value;
            }
        }
        
        /// <remarks/>
        public string OutboundTowards {
            get {
                return this.outboundTowardsField;
            }
            set {
                this.outboundTowardsField = value;
            }
        }
        
        /// <remarks/>
        public string OutboundVia {
            get {
                return this.outboundViaField;
            }
            set {
                this.outboundViaField = value;
            }
        }
        
        /// <remarks/>
        public string InboundPattern {
            get {
                return this.inboundPatternField;
            }
            set {
                this.inboundPatternField = value;
            }
        }
        
        /// <remarks/>
        public string InboundFrom {
            get {
                return this.inboundFromField;
            }
            set {
                this.inboundFromField = value;
            }
        }
        
        /// <remarks/>
        public string InboundTowards {
            get {
                return this.inboundTowardsField;
            }
            set {
                this.inboundTowardsField = value;
            }
        }
        
        /// <remarks/>
        public string InboundVia {
            get {
                return this.inboundViaField;
            }
            set {
                this.inboundViaField = value;
            }
        }
        
        /// <remarks/>
        public bool IsXpresso {
            get {
                return this.isXpressoField;
            }
            set {
                this.isXpressoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNitelink {
            get {
                return this.isNitelinkField;
            }
            set {
                this.isNitelinkField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMinimumFare {
            get {
                return this.isMinimumFareField;
            }
            set {
                this.isMinimumFareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class Destination {
        
        private int stopNumberField;
        
        private string typeField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private string descriptionField;
        
        private Route[] routesField;
        
        /// <remarks/>
        public int StopNumber {
            get {
                return this.stopNumberField;
            }
            set {
                this.stopNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Route[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class DestinationsResponse {
        
        private Destination[] destinationsField;
        
        /// <remarks/>
        public Destination[] Destinations {
            get {
                return this.destinationsField;
            }
            set {
                this.destinationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestServiceCompletedEventHandler(object sender, TestServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRealTimeStopDataCompletedEventHandler(object sender, GetRealTimeStopDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRealTimeStopDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRealTimeStopDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRealTimeStopData_ForceLineNoteVisitCompletedEventHandler(object sender, GetRealTimeStopData_ForceLineNoteVisitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRealTimeStopData_ForceLineNoteVisitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRealTimeStopData_ForceLineNoteVisitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRoutesCompletedEventHandler(object sender, GetRoutesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoutesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoutesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoutesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoutesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRoutesIncNiteLinkCompletedEventHandler(object sender, GetRoutesIncNiteLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoutesIncNiteLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoutesIncNiteLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoutesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoutesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRoutesIncNiteLink_MobileFareCalcCompletedEventHandler(object sender, GetRoutesIncNiteLink_MobileFareCalcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoutesIncNiteLink_MobileFareCalcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoutesIncNiteLink_MobileFareCalcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoutesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoutesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDestinationsCompletedEventHandler(object sender, GetDestinationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDestinationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDestinationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DestinationsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DestinationsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllDestinationsCompletedEventHandler(object sender, GetAllDestinationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDestinationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDestinationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DestinationsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DestinationsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStopDataByAddressCompletedEventHandler(object sender, GetStopDataByAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStopDataByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStopDataByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStopDataByRouteAndDirectionCompletedEventHandler(object sender, GetStopDataByRouteAndDirectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStopDataByRouteAndDirectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStopDataByRouteAndDirectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventHandler(object sender, GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStopDataByRouteAndDirection_MobileFareCalcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStopDataByRouteCompletedEventHandler(object sender, GetStopDataByRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStopDataByRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStopDataByRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRoutesServicedByStopNumberCompletedEventHandler(object sender, GetRoutesServicedByStopNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoutesServicedByStopNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoutesServicedByStopNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Route[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Route[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void StartTimerCompletedEventHandler(object sender, StartTimerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartTimerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartTimerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void StopTimerCompletedEventHandler(object sender, StopTimerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopTimerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopTimerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCurrentSettingsCompletedEventHandler(object sender, GetCurrentSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetCurrentSettingsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void postXMLDataCompletedEventHandler(object sender, postXMLDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postXMLDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postXMLDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ClearCacheItemCompletedEventHandler(object sender, ClearCacheItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearCacheItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClearCacheItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591